@startuml
'https://plantuml.com/class-diagram
left to right direction

class Task {
    long id
    long projectId
    String name
    long creationTimestamp
}

class Project {
    long id
    String name
    int color
}

Task "*"--"1" Project : is part of

@enduml