@startuml
'https://plantuml.com/use-case-diagram
left to right direction

Utilisateur as User


User ---> (Lister les tâches)
User ---> (Ajouter une tâche)
User ---> (Supprimer une tâche)

(Trier les tâches) as Tri

User ---> Tri
Tri ----> (Tri par ordre alphabétique)
Tri ----> (Tri par ordre alphabétique inversé)
Tri ----> (Tri par ordre de création)
Tri ----> (Tri par ordre de création inversé)




@enduml