@startuml
'https://plantuml.com/use-case-diagram
left to right direction

Utilisateur as User

User ---> (Lister les tâches)
User ---> (Ajouter une tâche)
User ---> (Supprimer une tâche)
User ---> (Trier les tâches)


@enduml